[book]
authors = ["Chris Titus"]
language = "en"
src = "src"
title = "DWM for Everyone"

[output.html]
additional-css = ["./theme/catppuccin.css","./theme/last-changed.css"]
default-theme = "latte"
preferred-dark-theme = "frappe"
print.enable = true
fold.enable = true
fold.level = 2

[output.pdf]
paper-width = 8
paper-height = 11

[output.epub]
# cover-image = "path/to/cover.jpg"
use-default-css = true

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4
